### ISSUE TITLE
Ability to run migrations outside of transactions

### ISSUE THREAD

**Issue by flyingmutant** [mattes/migrate#13]
For example, PostgreSQL can not add value to an enum (`ALTER TYPE t ADD VALUE 'v'`) inside a transaction.

See also: https://github.com/rails/rails/issues/9483.

**Comment by fedyakin** [comment]
We needed this functionality, as well as the ability to run all the scripts in a single transaction.  I've added that in a fork (github.com/fedyakin/migrate).  If you don't have a problem with the way we did it, I could integrate that change...

**Comment by mattes** [comment]
Interesting work! I totally agree on the ``ALTER TYPE ADD VALUE`` problem and that there should be a solution. 

In general I think the ``PerFileTxnDriver`` should be the default. This is how its implemented at the moment. I agree that there should be an option to disable transactions (``NoTxnDriver``). This should be done via a driver URL parameter, like 

```
migrate -url postgres://user@host:port/database?transactions=false -path ./db/migrations up
```

However, this would disable transactions for every migration. What we want is a way to disable transactions per file basis. I think a good work-around for this particular case would be to put a ``COMMIT;`` right at the top of the migration file. I guess this should do the trick.

Regarding the ``SingleTxnDriver``: I think each migration file is one atomic unit that migrates the database from one state into another - up and down. So I  don't think there is a need for an option to spawn one single transaction over all migration files to be run. What is your use-case?

**Comment by fedyakin** [comment]
I agree that the current behavior (PerFile) should be the default.  

Specifying transaction behavior via the url seems like a better way to set the option than via command line.  Especially since support for the option is driver specific (Not all databases support transactional ddl).

You are right, that running with the flag would disable transactions for all files.  We intend to run the migration tool twice; once with the path set to a directory of non-transactional scripts and once with scripts that can run in a transaction.

We have a couple different use cases for the single transaction behavior.  Every time we run the migration tool we have it destroy and recreate all stored procedures on top of any ddl/dml changes (Our fork added an always run feature I assumed no one else needs).   We want to have all those changes occur together, or not at all.

A use case that might be more common to other people, is deploying to live an application that requires multiple new database versions.  If any of the database scripts fail, we want the database to be unaltered.  That way the current version of the application can remain running.

I understand if you don't want to bring this implementation back to the main depot.  Hopefully it at least hints at a fairly simple way to solve the original poster's feature request :-)

**Comment by alfredr** [comment]
After thinking about this, I think having a transaction around the ALTER TYPE is important for consistency. This can be achieved instead by:
1) creating a second temporary enum type
2) altering the table column type to the temp type
3) dropping the old one
4) renaming the temp one.

**Comment by gravis** [comment]
I think the best option would be to support `.go` migrations files along with the current one (see #88).
This would allow the user to disable the transaction if needed, like rails does https://github.com/rails/rails/issues/9483

**Comment by juri** [comment]
Just another data point: another case where this is needed is adding indexes with PostgreSQL, and I don't think there's a workaround. I just tried adding an index and I wanted to have it run without locking the db, but PostgreSQL informed me that `ERROR 25001: CREATE INDEX CONCURRENTLY cannot run inside a transaction block`.

**Comment by ojrac** [comment]
I'm also having this problem for CREATE INDEX CONCURRENTLY. fedyakin's solution doesn't work that well for me: I still want most of my migrations to run in a transaction. So, I also forked, and implemented my take on it: https://github.com/demiurgestudios/migrate/commit/56c9505338550c7cd029ee96e1916f9bab2ce645

I check for a "-- migrate: no-transaction\n" at the beginning of a migration file to signal a migration should run outside a transaction. It's a little brittle, but I'm not sure that's a bad thing; this is all to avoid an extremely noisy failure.

There was one small related change: updating the "version" table happens after the migration finishes, so a non-transactional failure won't keep running migrations until someone manually fixes the migration.

**Comment by mattes** [comment]
I don't think this is the way forward, as we don't want to have custom configuration state managed by migrate.

```
-- migrate: no-transaction\n
```

v3 postgres driver won't wrap migrations in transactions allowing ` CREATE INDEX CONCURRENTLY` to happen. eventually applying a two phased commit. more docs to follow.

**Comment by ryankask** [comment]
I installed the latest v3 release candidate after seeing a link in the README but I was surprised that each migration wasn't run in a transaction although I understand that not all statements are allowed in a transaction.

Are you planning on shipping v3 without a transaction solution?

If that's the case, what are the advantages of v3 over v2 if running each migration in a transaction is a requirement? If I'm using Postgres, does v2 have any major issues?

Thanks!

**Comment by mattes** [comment]
yes, that's the expected behavior in v3. if you need a transaction, use BEGIN/COMMIT in the actual migration. migrate still has you covered in case something fails with a "dirty" state.
