### ISSUE TITLE
Rollback strategy

### ISSUE THREAD

**Issue by varunrau** [mattes/migrate#254]
What's the recommended strategy for handling rollbacks? Perhaps we could document this ☺️

**Comment by ifraixedes** [comment]
_down_ migrations are for such purpose.

The issue is that if you have deployed in production, the rollback may not only need to remove the part of the schema that the migrations has made, because it may happen that some data has been inserted and depending of the changes that the schema has suffered in the migration, you may want to do some thing (update, move, backup, etc.) with data rather than just destroying it.

**Comment by JensRantil** [comment]
@varunrau: @ifraixedes answered your question, right? I believe this issue can be closed.

**Comment by varunrau** [comment]
oops sorry missed the reply. Yeah we can close this
